### ISSUE TITLE
Search method

### ISSUE THREAD

**Issue by kiru** [sergkr/rtreelib#4]
Hello @sergkr , 

Thank you for this library! 

I was wondering why there is no search method implemented?

something like`tree.search(Rect(0, 0, 300, 300))` would return all entires

Thank you, 
Kiru

**Comment by cgmike** [comment]
This library is interesting, but I agree that a search method would be most helpful! It's a bit difficult to use without one.

**Comment by kiru** [comment]
I use the following methods right now to get the matching nodes:

```
def visit_child(node, rect):
    if(node.is_leaf):
        yield node

    for entry in node.entries:
        intersection = entry.rect.get_intersection_area(rect)
        if(intersection > 0):
            yield from visit_child(entry.child, rect)
            
def search(tree, rect):
    yield from visit_child(tree.root, rect)

```

**Comment by lukas-shawford** [comment]
Sorry for the delay - finally got some time to work on this today.

I just pushed a new version (0.2.0) which adds querying methods. If you're able to give these a try, let me know how they work for you. I added a new "Querying" section to the README with some examples.

I'll go ahead and close this out, but let me know if you see any issues with the implementation.

**Comment by kiru** [comment]
Hello @sergkr 
Thank you very much for the quick implementation. I didn't expect it to get an updated this fast.

The new `Point` class is interesting. I was expecting to be able to add a new Point as well, such as:
`my_tree.insert("A", Point(10, 10))`
Doing so breaks the get_bounding_box() method
```
my_tree = RTree()
my_tree.insert("A", Point(1, 1))
my_tree.insert("B", Rect(3, 3, 4, 4))
print(my_tree.root.get_bounding_rect()) # error 'Point' object has no attribute 'union' 
```

I tested the query method and found this unexpected behaviour: 
```
my_tree = RTree()
my_tree.insert("A", Rect(1, 1, 1, 1))
my_tree.insert("B", Rect(3, 3, 4, 4))
print(my_tree.root.get_bounding_rect())
print(list(my_tree.query(my_tree.root.get_bounding_rect())))
```
The above snippet prints: 
```
Rect(1, 1, 4, 4)
[RTreeEntry(0x136c817f0, data=B)]
```
This is intended as you describe: "When querying by point, note that points that lie on the border (rather than the interior) of a bounding rectangle are considered to intersect the rectangle."

Is there a way to overwrite this? In the above example, intuitively I would expect to get all objects in the rtree. 

Edit: Another example which is not clear to me: 

```
my_tree = RTree()
my_tree.insert("A", Rect(1, 1, 1, 1))
my_tree.insert("B", Rect(2, 2, 2, 2))

print(list(my_tree.query(Rect(0, 0, 5, 5)))) # is [] but expected "A" and "B"

# debug
found = list(my_tree.query_nodes(Rect(0, 0, 5, 5))) # returns one node
for x in found:
    for b in x.entries:
        print(b.rect.intersects(Rect(0, 0, 5, 5))) # always False

```


Thank you, 
Kiru

**Comment by lukas-shawford** [comment]
Thanks @kiru - I created 3 issues based on your comment, and will tackle them separately:

#5: Allow inserting Point entries
#6: Handle "degenerate" rectangles
#7: More flexible query options (equals, contains, within, intersects, overlaps, touches)

Of these, the last one will almost certainly be the most challenging (and also the most interesting). I think I'm done for today, but I'll try to pick this back up next weekend.

If you have any input, just leave a comment where appropriate.

**Comment by kiru** [comment]
Thank you very much!
